# Generated by Django 4.1.7 on 2023-04-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_orders_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='complete_order',
            field=models.BooleanField(default=False, null=True, verbose_name='Выполнен'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='products', to='store.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
