# Generated by Django 4.1.7 on 2023-04-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orders_complete_order_alter_cart_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(height_field=200, upload_to='', verbose_name='Фото', width_field=200),
        ),
    ]
