# Generated by Django 4.1.7 on 2023-04-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='summ',
            field=models.IntegerField(blank=True, verbose_name='Цена заказа'),
        ),
    ]
