# Generated by Django 4.1.7 on 2023-04-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cart_products_alter_cart_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='summ',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена заказа'),
        ),
    ]
